language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

notifications:
    email: dev@anime-db.org

before_script:
    - composer self-update
    - composer install --dev --prefer-dist

script:
    - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
