parameters:
    anime_db.ani_db.host: 'http://anidb.net'
    anime_db.ani_db.cache.dir: '%kernel.cache_dir%/ani_db_response/'
    anime_db.ani_db.cache.requests:
        anime: '+1 week'
        categorylist: '+6 month'
        randomrecommendation: ~
        randomsimilar: ~
        mylistsummary: ~
        hotanime: '+1 day'
        main: '+1 day'
